# Travis CI Setup
# Adapted from https://github.com/greghendershott/travis-racket

language: c

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=7.6

install:
  - bash <(curl https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh)
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
  - raco test -x .
