# Travis CI Setup

# Adapted from:
# * https://github.com/greghendershott/travis-racket
# * https://github.com/codecov/codecov-racket

language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=7.6

install:
  - bash <(curl https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh)
  - export PATH="${RACKET_DIR}/bin:${PATH}"

script:
  - raco test -x .

after_success:
  - raco pkg install --deps search-auto cover cover-codecov
  - raco cover -f codecov -d $TRAVIS_BUILD_DIR/coverage .
